### ISSUE TITLE
이미지 추론시 전체 이미지 갯수가 성능에 미치는 영향 분석

### ISSUE THREAD

**Issue by hyu-leeky** [ddps-lab/edge-inference#13]
각기 다른 이미지 10000 장을 특정 배치사이즈로 모두 추론 할때와
배치 사이즈 만큼의 이미지를 준비 후 해당 이미지를 반복적으로 추론할 경우 추론 성능 비교 분석

**Comment by jungae-park** [comment]
[추가 실험 필요 대상]

TX1 장비
inception v3 (batch size 64,128)
Nano 장비
mobilenet v1 (batch size 64,128)
mobilenet v2 (batch size 32,64,128)
inception v3 (모든 batch size)
[기존 실험]

1000장의 이미지를 batch size 만큼 추론 진행
(batch size가 32일 경우, 각기 다른 32장의 이미지를 약 30번 추론 진행)
[추가 실험]

1000장의 이미지 중 batch size 만큼의 같은 이미지 (32장 or 64장)를 batch size 만큼 추론 진행

**Comment by jungae-park** [comment]
* nano 장비에서 mobilenet v1 모델 기준 실험 진행 

[batch size 8]
1. 기존 실험 결과 
accuracy : 0.93
model_load_time = 69.93868399 
dataset_load_time = 2.046374798
inference_time = 62.63308215
inference_time(avg) = 0.05643707871
IPS = 7.42839512 
IPS(inf) = 17.71884766

2. 추가 실험 결과
accuracy = 0.875
model_load_time = 71.55842232704163
dataset_load_time = 2.267603874206543
inference_time = 56.64110779762268
inference_time(avg) = 0.03866882061958313
IPS = 7.664753829697004
IPS(inf) = 25.860628381657133

[batch size 32]
1. 기존 실험 결과 
accuracy : 0.93
model_load_time = 70.3433439731597 
dataset_load_time = 2.06814813613891
inference_time = 107.153173446655
inference_time(avg) = 0.0860108092892915
IPS = 5.70267358111255 
IPS(inf) = 11.626445655645

2. 추가 실험 결과
accuracy = 0.90625
model_load_time = 71.08581304550171
dataset_load_time = 2.2160375118255615
inference_time = 78.59936690330505
inference_time(avg) = 0.05922929445902506
IPS = 6.319859373607144
IPS(inf) = 16.883537261984472

[결과 비교]
- nano 장비 자체가 메모리를 사용하고 해제하는 기능이 다른 장비에 비해 떨어짐
(캐시 삭제, 재부팅 필요)
- batch size 8을 기준으로 실험1,2를 비교하였을 때, accuracy는 0.5 정도 감소하였고 IPS는 비슷하지만 IPS(inf)는 8정도 차이가 있음 (memory = 0.3*1024)
- batch size 32를 기준으로 실험 1,2를 비교하였을 때, accuracy는 0.3 정도 감소하였고 IPS는 1, IPS(inf)는 5정도 차이가 있음 (memory = 0.5*1024)
- 실험과 별개로 batch size에 따라 GPU에 할당해야하는 메모리는 정해져 있음
실험 시나리오가 달라졌다고해서 메모리를 적게 할당해도 되는 것은 아니였음
- 코드가 비효율적으로 작성되었는지 확인 필요

**Comment by hyu-leeky** [comment]
정애야 그러면 같은 배치를 여러개 보냈을때 이전에 안되던 배치 사이즈 (예: 128) 가 추가 실험 (같은 배치를 계속 보내는 경우) 에서는 동작이 가능한 경우가 있었어?

**Comment by jungae-park** [comment]
같은 batch size (64,128)을 여러개 추론을 진행하여도, 이전 처럼 메모리 부족으로 killed 되었습니다.
제가 작성한 코드는 아래와 같습니다.
```
iftime_start = time.time()
    for i, (validation_ds, batch_labels, _) in enumerate(dataset):
        if i == 0:
          test_data = validation_ds
          for i in range(0,7):
            print(i)
            start_time = time.time()
            pred_prob_keras = model(test_data)
            iter_times.append(time.time() - start_time)

            actual_labels.extend(label for label_list in batch_labels.numpy() for label in label_list)
            pred_labels.extend(list(np.argmax(pred_prob_keras, axis=1)))
          
            if i*batch_size >= display_threshold:
                display_threshold+=display_every
            
    iter_times = np.array(iter_times)
    acc_keras_gpu = np.sum(np.array(actual_labels) == np.array(pred_labels))/len(actual_labels)
```
코드는 dataset 1000장에서 무작위로 128개의 한 batch를 가져와서 1000장을 추론 한 것 만큼 반복 횟수를 지정하여 진행하였습니다.
코드가 비효율적으로 작성이 되어 메모리 부족으로 실행이 안되는 경우인지 확인을 추가로 하고있습니다.
