### ISSUE TITLE
모든 NLP 모델을 TFLite로 Convert하고, 다양한 Batch 단위로 추론 가능하도록 코드 작성

### ISSUE THREAD

**Issue by unhochoi** [ddps-lab/edge-inference#15]

**Comment by unhochoi** [comment]
- NLP 모델(hdf5)을, 향후 사용할 batch 단위 별로 개별 저장해놓는 방향으로 구현
    - NLP 모델(hdf5)은, 향후 tflite 에서 사용할 배치 입력 형식과 동일한 입력 형식이 포함되어있어야함
    - 예를 들어, tflite 로 Convert 한 뒤 배치 사이즈 2로 추론하고 싶다면, tflite 로 convert 하기 전, 원본 모델의 입력 형식이 배치 사이즈 2로 설정되어 있어야함
    - [https://github.com/ddps-lab/edge-inference/blob/a7e7b4a4c674febdaed6227ebc210e90c1233f8e/NLP/rnn_imdb_tflite.py#L14](https://github.com/ddps-lab/edge-inference/blob/a7e7b4a4c674febdaed6227ebc210e90c1233f8e/NLP/rnn_imdb_tflite.py#L14)
- 향후, 하나의 tflite 모델만을 사용하기 위해, resize_tensor_input 등을 사용해 모델 입력을 동적으로 처리할 수 있는 방법을 파악해야함

**Comment by hyu-leeky** [comment]
오케이. 그렇다면 지금의 코드에서는 가변적으로 배치 사이즈를 설정할수는 없고, 원본 모델을 학습할때부터 특정 배치 사이지를 입력 받게끔 학습이 되어야 한다는 이야기인거야? 아니면 모델은 하나가 있고 그걸 tflite 로 변경하면서 배치 사이즈를 결정해줘야 하는거야?

**Comment by unhochoi** [comment]
넵, 후자로 진행하는게 효율적이기 때문에 후자로 진행하려했으나 생각보다 쉽게 해결되지 않아 우선 전자로 진행중입니다.

**Comment by hyu-leeky** [comment]
오케이. 그렇다면 각기 다른 배치 사이즈마다 학습이 새롭게 일어나야 하는구나. 그렇다보니 학습 코드도 당연히 필요한것 같고. 
학습에 소요되는 시간 및 정확도는 어떻게 될까? 구현이 오래 걸린다면 우선 지금 형태로 진행을 하는건 괜찮을것 같아. 다만 새롭게 학습을 하면서 모델의 정확도 및 처리 성능의 차이까지 영향을 미치지 않을까 하는 염려가있기는 하네. 우선 이번 pr 은 머지를 하도록 하고 이번에 완료 못한 기능은 새로운 이슈로 만들어두도록 하자.

**Comment by unhochoi** [comment]
- 학습을 반복함으로써 모델 정확도가 변환되는 것을 막기 위해, 학습된 원본 모델을 로드한 뒤, 입력 형식만 추가로 할당해 다시 저장하는 방식으로 구현하고 있습니다.
- 진행되는 순서는 아래와 같습니다.
    - hdf5 형식의 원본 모델을 로드 → 배치에 따른 입력 형식을 추가한 뒤 pb 형식으로 모델 저장 →
    - 입력 형식이 추가된 pb 형식의 모델 로드 → tflite 로 convert → tflite 저장
    - 참고 링크 (9번~25번 라인)
        - [https://github.com/ddps-lab/edge-inference/blob/aff75c8d456c5eb7c76a5a4eba590398ea036e3d/NLP/rnn_imdb_tflite.py#L9](https://github.com/ddps-lab/edge-inference/blob/aff75c8d456c5eb7c76a5a4eba590398ea036e3d/NLP/rnn_imdb_tflite.py#L9)
- 따라서, 모델 정확도가 변경되진 않습니다.

**Comment by unhochoi** [comment]
- DistilBERT 를 TFLite 로 변환하는 과정 진행 중
    - 입력 형식 관련한 문제가 발생해 해결 진행 중

**Comment by unhochoi** [comment]
- DistilBERT를 TFLite로 Convert 하는 작업은 완료했으나, 정확도가 50%로 밖에 안 나오는 문제 발생 중
    - 해당 문제의 원인을 파악하고 있으나, 동일한 문제가 발생하는 외부 이슈를 발견함
        - [https://github.com/huggingface/tflite-android-transformers/issues/11](https://github.com/huggingface/tflite-android-transformers/issues/11)
        - [https://github.com/tensorflow/tensorflow/issues/43719](https://github.com/tensorflow/tensorflow/issues/43719)
- BERT를 TFLite로 Convert 하는 작업 진행 중

**Comment by hyu-leeky** [comment]
오케이. 해당 이슈에 잘 정리가 되어있네. weight 값이 fp16 의 범위를 넘어가버려서 이상한 값으로 치환되는. 그럴듯 하다. 그런데 저 이슈는 2020년 말에 close 가 된것 같은데. 그렇다면 우리 환경에서는 문제가 없어야 하지 않을까? 사실 우리는 정확도 보다는 처리 성능이 더 중요하기는 한데.. 정확도가 그렇게 많이 떨어진다니 이슈가 있을것 같기도 하네.

**Comment by unhochoi** [comment]
어떤 방식으로 해결할 수 있는지 좀 더 파악해보겠습니다.

**Comment by hyu-leeky** [comment]
이전 이슈와 많이 비슷해보니 우선 버전등을 위주로 해서 보는게 좋을것 같기는 하다.

**Comment by unhochoi** [comment]
넵,알겠습니다.

**Comment by unhochoi** [comment]
- DistilBERT를 TFLite로 Convert 한 뒤, Coral-TPU 에서 배치 단위별 추론 성능을 측정해보았습니다.
- 1 ~ 64 배치까지만 실행이 완료되었으며, 128 배치부턴 메모리 부족으로 Killed 되었습니다.
- 우선, 해당 결과값은 시트에 업데이트 해두었으며,
- 해당 실험은 Edge-TPU 용 TFLite 모델이 아닌, FP32 TFLite 모델로 진행했으므로, 추가적인 실험이 필요합니다.

**Comment by unhochoi** [comment]
Coral TPU 지원 NLP Operation 문제로 인해 해당 이슈는 Close
