### ISSUE TITLE
TFLite로 Convert한 모델이 Coral TPU에서 정상적으로 동작하는지 확인 필요

### ISSUE THREAD

**Issue by unhochoi** [ddps-lab/edge-inference#16]

**Comment by unhochoi** [comment]
- TFLite 로 변환한 RNN, LSTM 모델이 잘 동작하는지 확인 필요
    - 기존의 Coral TPU 장비에서 CNN, NLP 실험을 동시에 진행하기 어려워,
    - 별도의 Coral TPU 장비를 추가로 붙이고 있으나,
    - 장치 초기화 과정이 정상적으로 진행되고 있지 않아 지연되고 있는 상태

**Comment by hyu-leeky** [comment]
혹시 tpu 장비가 추가로 필요하면 내 방에 하나 있으니 그걸 가지고 가서 사용해도 괜찮을것 같아. 필요하면 알려줘.

**Comment by unhochoi** [comment]
넵, 알겠습니다.

**Comment by unhochoi** [comment]
RNN, LSTM TFLite 모델이 Coral TPU에서 정상적으로 동작하는 것을 확인해, 추론 성능 측정 중

**Comment by unhochoi** [comment]
- Distilbert TFLite 를 사용한 배치 추론 코드 작성 완료
    - 정확도 문제는 해결되지 않은 상태
    - Coral-TPU 에서 성능 측정할 계획

**Comment by unhochoi** [comment]
Coral TPU 지원 NLP Operation 문제로 인해 해당 이슈는 Close
