### ISSUE TITLE
imagenet dataset을 batch 단위별로 tfrecord 생성 작업

### ISSUE THREAD

**Issue by jungae-park** [ddps-lab/edge-inference#21]
각 batch size 만큼의 데이터만 메모리에 로드하여 추론 작업을 진행하기 위해 원본 imagenet dataset을 batch 단위 별로 tfrecord로 생성하여 추론 진행
참고 코드 : https://github.com/kmonachopoulos/ImageNet-to-TFrecord/blob/master/build_imagenet_data.py

**Comment by hyu-leeky** [comment]
이 이슈가 #13  과 연관되어 있는듯 하고, 이게 해결 되어야 앞으로 실험 시나리오를 확정해나갈것 같은 생각이 들거든. 이 이슈에 대한 업데이트는 없을까?

**Comment by jungae-park** [comment]
https://github.com/ddps-lab/edge-inference/issues/13
현재 작업 사항을 말씀드리면, tfrecord로 변환하기 전 원본 이미지를 batch siz(1,2,4,8,16,32,64,128)에 맞게 자르고 tfrecord로 변환하여 데이터를 사용할 수 있도록 작업을 진행하고 있습니다.
그런데 모든 사이트에서 이미지 제공 기간이 끝나 다운로드를 받을 수 없는 이슈가 있었습니다. 현재 재강이가 s3에 올려둔 원본 이미지를 발견하여 이 이미지를 활용하여 작업을 진행하고 있습니다.
edge tpu 코드 업로드 및 이슈 사항 공유 후, 자세한 작업 내용을 공유 드리겠습니다.
(이쪽 이슈와 내용이 비슷한 점이 있습니다.)

**Comment by hyu-leeky** [comment]
오케이. 원본 이미지를 구하지를 못했구나. 일 차근 차근 진행하면서 알려줘도 될것 같아~

**Comment by jungae-park** [comment]
우선, tfrecord가 무엇인지 다시 살펴 보았고, 사용시 장점을 알아보았습니다.

* tfrecord
텐서플로의 데이터 형식중 하나이고, 원본 이미지와 라벨값이 포함된 형태이다.
* tfrecord 사용시 장점
reading 속도가 빠르다.
원본 데이터를 안전하게 보관하고 전처리 된 결과물을 tfrecord로서 활용할 수 있다.
하나의 file로 수많은 데이터를 묶을 수 있다.

tfrecord가 메모리 절약에 영향이 있는지 정확하지 않지만, 
현재 실험 환경인 edge 장비에서 tfrecord로 변환하여 사용하여도 메모리 부족 현상이 일어나는 상황입니다.
그래서 원본 이미지를 구했으니 원본 이미지로는 edge tpu 환경에서 추론하는 작업을 통해 입력 형식 이슈를 해결하고 동시에 batch size 만큼 tfrecord로 변환하여 tx1, nano 환경에서 못다한 추론하는 작업을 같이 진행해보는게 좋을 것 같다는 생각이 듭니다.

추후에 edge 환경에서 실험을 다시 진행해야 하더라도 edge tpu 환경에서 사용하였던 코드를 model만 바꿔서 진행할 수 있도록 작업을 진행 할 예정입니다.

**Comment by hyu-leeky** [comment]
"현재 실험 환경인 edge 장비에서 tfrecord로 변환하여 사용하여도 메모리 부족 현상이 일어나는 상황입니다." 여기서 말하는 tfrecord 로 변환 된건 전체 이미지 (1000장 혹은 50000장) 가 모두 포함된 하나의 큰 tfrecord 인거지?
그렇다면 배치 사이즈만큼 tfrecord 재구성 혹은 원본 이미지를 그대로 사용해서 실험을 진행해보기는 해야겠다. 둘다 구현이 만만치 않을수 있겠지만, 어느정도 진행이 된것 같으니 조금만 더 시도해보자.

**Comment by jungae-park** [comment]
네 전체 이미지가 포함된 큰 tfrecord 입니다.
배치 사이즈 만큼 tfrecord 구성과 원본 이미지 그대로 사용 실험을 시도해보겠습니다.

**Comment by jungae-park** [comment]
imagenet dataset을 tfrecord로 batch size별로 변환하는 과정에서 참고하는 코드가 TF v1로 작성되어 v2로 고치는 이슈가 있었지만 batch size 별로 tfrecord 변환을 완료하였습니다.
같은 batch size 일때 기존 실험 결과와 IPS(image per second) 값이 같은지 비교해보고,
batch size가 늘어날 때 메모리 부족 현상이 똑같이 일어나는지 확인하고 있습니다.
확인 후 결과를 다시 공유하겠습니다.

**Comment by hyu-leeky** [comment]
나이스!

**Comment by jungae-park** [comment]
- batch size imagenet to tfrecord
    - 원본 imagenet validation dataset은 1000개의 class를 가지고 있고, 각 class 마다 50개의 이미지가 있어 총 50000장입니다.
    - 1000장 짜리 tfrecord는 1000개의 class에서 각 class의 이미지를 1장씩 추출하여 이미지 1000장을 tfrecord로 변환한 것 입니다.
    - 새로운 실험을 위해, batch 단위별로 앞에서부터 순차적으로 1,2,4,8,16,32,64,128개의 class에서 이미지를 1장씩 추출하여 tfrecord로 변환하였습니다.

```
 for i, (validation_ds, batch_labels, _) in enumerate(dataset):
        print(len(validation_ds)) 
        if i == 0:
          test_data = validation_ds
          for i in range(0,30):
            print(i)
            start_time = time.time()
            pred_prob_keras = model(test_data)
            iter_times.append(time.time() - start_time)

            actual_labels.extend(label for label_list in batch_labels.numpy() for label in label_list)
            pred_labels.extend(list(np.argmax(pred_prob_keras, axis=1)))
          
            if i*batch_size >= display_threshold:
                display_threshold+=display_every
            
    iter_times = np.array(iter_times)
    acc_keras_gpu = np.sum(np.array(actual_labels) == np.array(pred_labels))/len(actual_labels)
```
그래서 위의 코드를 활용하여 실험을 진행하였습니다.
- batch size 32 (하나의 mini batch) * 31(0-30)번 = 총 992번
```
# 기존 실험 (0.5*1024 memory)
***** TF-FP32 matric ***** 
user_batch_size = 32
accuracy = 0.93
model_load_time = 70.3433439731597
dataset_load_time = 2.06814813613891
inference_time = 107.153173446655
inference_time(avg) = 0.0860108092892915
IPS = 5.70267358111255
IPS(inf) = 11.626445655645

# 새로운 실험 (0.5*1024 memory)
1. 
***** TF-FP32 matric *****
user_batch_size = 32
accuracy = 0.875
model_load_time = 70.45441937446594
dataset_load_time = 2.007218837738037
inference_time = 85.81826090812683
inference_time(avg) = 0.0723131999373436
IPS = 6.065193702528673
IPS(inf) = 13.828733908421405

2. 
***** TF-FP32 matric *****
user_batch_size = 32
accuracy = 0.875
model_load_time = 71.17397260665894
dataset_load_time = 2.0298333168029785
inference_time = 84.84894323348999
inference_time(avg) = 0.04852566222349803
IPS = 6.073890861692349
IPS(inf) = 20.607652820774096

3. 
***** TF-FP32 matric *****
user_batch_size = 32
accuracy = 0.875
model_load_time = 69.94255924224854
dataset_load_time = 2.027876138687134
inference_time = 60.49587154388428
inference_time(avg) = 0.04638319263855616
IPS = 7.247113088578526
IPS(inf) = 21.559533596416284
```
- 결과 분석
    - IPS 값이 기존 실험과 비교할 때 최소 1장 - 최대 10장 정도 차이가 납니다.
    - 같은 설정으로 반복 실험하면 IPS 값이 바뀌고, count 할 때 누락 되는 부분도 보입니다. (불안정)
    
- batch size 64, 128은 메모리 부족으로 실행되지 않았는데, 새로운 실험에서도 메모리 부족하여 실행이 되지 않고 killed 되었습니다. (gpu에 메모리가 부족한 것과 다르게 killed 에러를 내뱉고 끝남)
    - batch size 64 : 0.8*1024 memory, 16번(0-15), 총 1024번 (불가능)
    - batch size 128 : 0.8*1024 memory, 8번(0-7), 총 1024번 (불가능)

- tfrecord를 사용하는 것이 메모리 절약에 영향이 있는지 아직도 의문이고 실험 결과값이 불안정하며 batch size가 커지면 메모리 부족 현상이 똑같이 발생합니다.
- 그래서 tfrecord dataset을 사용하는 것이 의미가 없어 보이므로 원본 이미지로 추론도 진행해보려고 합니다.

**Comment by jungae-park** [comment]
batch szie에 따른 tfrecord 데이터를 사용하여도 64,128 배치에서는 메모리 부족 현상이 똑같이 발생하므로 더 이상의  실험은 진행하지 않고 이슈를 close 하겠습니다.
