### ISSUE TITLE
TX1 장비에서 BERT 추론 시 에러

### ISSUE THREAD

**Issue by unhochoi** [ddps-lab/edge-inference#22]

**Comment by unhochoi** [comment]
메모리 부족으로 인해, 16 배치 이상의 추론부턴 Killed 되고 있는 상태

**Comment by hyu-leeky** [comment]
TX2 는 문제가 없고 TX1 에서만 문제가 발생하는거지? TX1 이 계속 문제가 발생하는 걸 봐서 실험에서 제외를 하는게 맞을것 같다는 생각이 들기도 하네.

**Comment by unhochoi** [comment]
네, TX2 에서는 문제가 없었습니다.
