### ISSUE TITLE
tpu image classfication infernece 에서 입력 형식 에러

### ISSUE THREAD

**Issue by jungae-park** [ddps-lab/edge-inference#23]
우선, mobilenet v1 모델을 기준으로 코드를 작성하고 있으며 이슈가 있어 코드와 함께 에러를 공유합니다.

**Comment by jungae-park** [comment]
업로드하는 코드를 활용하여 edge 환경에서 추론 작업을 진행하던 중 이슈가 발생하였습니다.
모델을 로드하고 input 데이터를 가져와 추론하는 과정의 입력 형식 부분에서 에러가 발생하고 있어 해결하고 있습니다.

coral 홈페이지에서 제공하는 코드를 참고하여 작업을 진행하고 있으며,
https://github.com/google-coral/tflite/blob/master/python/examples/classification/classify_image.py 
참고하고 있는 코드 뿐만 아니라 대부분 추론 작업 코드를 보면 이미지 데이터를 tfrecord로 변환하지 않고, 원본 데이터를 불러와 추론 작업을 하고 있었습니다. 
tfrecord로 변환하여 입력 형식에 맞추는 문제도 있고, 추가로 실험해야하는 부분에서 tfrecord를 batch size 만큼 잘라서 사용하도록 하는 작업도 해야하는 상황에서 tfrecord로 변환하여 사용하는것이 맞는 방법인지 의문이 들어 tfrecord를 사용하는 이유에 대해 좀 더 살펴보고 있으며 에러를 확인하고 있습니다.

**Comment by hyu-leeky** [comment]
그러게 정애야. 내가 생각해도 왜 굳이 tfrecord 를 사용해야 하나 싶기는 해. 그냥 원본 이미지를 바로 대입하면 편할것 같아서. 조금 더 알아보자.

**Comment by jungae-park** [comment]
기존 tfrecord 데이터셋으로 tpu 환경에서 추론을 진행하였으나, 입력 형식 에러가 발생하는 이슈가 있어
원본 이미지 추론을 시도하고 있습니다.
우선 기본적으로 coral에서 제공하는 기본 예제가 제대로 실행되는지 확인하였는데 추가적인 런타임 에러 이슈가 발생하여 확인하고 있습니다.

- 원본 이미지 추론 (coral 에서 제공하는 mobilnet v2 모델 추론 예제)
    [https://github.com/google-coral/tflite/blob/master/python/examples/classification/classify_image.py](https://github.com/google-coral/tflite/blob/master/python/examples/classification/classify_image.py) (참고)
    
- 이슈 발생
    - 런타임 에러 발생 
        - 런타임 버전 문제라고 생각되어 확인중
        [https://github.com/google-coral/tflite/issues/21](https://github.com/google-coral/tflite/issues/21)
        
        ```bash
        RuntimeError: Internal: Unsupported data type in custom op handler: 0Node number 1 (EdgeTpuDelegateForCustomOp) failed to prepare.
        ```

**Comment by jungae-park** [comment]
* tfrecord imagenet 데이터를 사용하여 edge tpu 환경에서 추론 
위의 에러가 원본 이미지를 사용하였을 때 발생하였던 이슈였는데, tfrecord 데이터를 사용하면서도 발생하여 이슈를 확인해보았습니다. (런타임 버전 에러)
기존 설치된 런타임은 python 3.8에 해당하는 버전으로 현재 사용중인 python 3.6 버전과 맞지 않아서 생긴 이슈였습니다.
따라서, python 3.6 버전에 맞는 tflite-runtime 버전을 설치하여 이슈를 해결하였습니다.
https://github.com/google-coral/edgetpu/issues/68

tfrecord 데이터를 사용하여 edge tpu 환경에서 추론을 하기 위한 fix된 환경 설정을 다시 아래와 같이 정리해보았습니다.

* 설치해야하는 라이브러리
1. libedgetpu1-std (v15.0)
2. python3-edgetpu(v15.0)
3. tflite-runtime (v2.1.0)

* tpu를 사용하여 추론하기 위해 모델과 라이브러리 설정 
모델은 edge tpu용으로 convert된 모델을 사용하는 것이 맞고, dtype은 확인하였을 때 int8이였습니다.
그리고 라이브러리를 설정해주어야 tpu 환경에서 추론이 진행됩니다.
```
from tflite_runtime.interpreter import Interpreter
from tflite_runtime.interpreter import load_delegate
model = Interpreter("./mobilenet_v1_edgetpu.tflite", experimental_delegates=[load_delegate('libedgetpu.so.1')])
```

위의 fix된 환경에서 tfrecord imagenet 데이터를 사용하여 edge tpu 환경에서 추론하는 코드를 계속 작성하고 있습니다. 
현재는 입력 형식 에러를 해결하고 있으며, 해결 과정도 다시 공유하겠습니다.

**Comment by jungae-park** [comment]
dtype이 float 32인 tfrecord imagenet 데이터셋을 모델과 같은 dtype int8로 아래와 같이 변경하여 이슈를 해결하였습니다.
```
input_data = tf.cast(validation_ds, tf.uint8)
```

**Comment by hyu-leeky** [comment]
오케이. 그렇다면 tpu 에서 구동 중 문제였던 입력 형식 문제는 해결이 된듯 하네. 추가적인 문제가 발견되지 않는다면 tpu 에서 이미지 관련한 실험을 비롯해서 모든 실험 완료가 되는거지?지금은 tf record 사용이야? 아니면 원본 이미지 사용이야?

**Comment by jungae-park** [comment]
tfrecord를 사용하여 int8로 입력 형식 문제를 해결하였습니다.
구동만되고 정확도와 batch size 문제가 생겨 추가로 살펴보고있습니다.
