### ISSUE TITLE
inception v3 모델 tflite(int8)로 convert 후 edgetpu 컴파일 

### ISSUE THREAD

**Issue by jungae-park** [ddps-lab/edge-inference#33]
https://github.com/ddps-lab/research-issues/issues/45
TF2로 작성된 inception v3 모델을 int8 형식인 tflite로 convert후 tpu 환경에서 사용 가능하도록 edgetpu 컴파일을 진행하려고 합니다.

**Comment by jungae-park** [comment]
tf2로 작성된 inception v3 모델을 int8 형식의 tflite로 convert 하였고, 정상적으로 edgetpu로 컴파일 완료하여 모델을 생성하였습니다.
자세한 작업 절차는 아래 노션으로 정리하였습니다.
https://encouraging-lantern-5d1.notion.site/inception-v3-model-convert-to-int8-tflite-edgetpu-compiler-d28c2d83e85440cb9cae801a80188436

따라서 이미지 한 장, 여러장에 대해 추론을 진행해보았고 아래와 같은 결과를 얻었습니다.
- 한 장

```bash
----INFERENCE TIME----
Note: The first inference on Edge TPU is slow because it includes loading the model into Edge TPU memory.
740.1ms
562.4ms
584.9ms
577.2ms
570.0ms
-------RESULTS--------
n01601068	satin bowerbird, satin bird, Ptilonorhynchus violaceus: 0.73828
```

- 여러장

```bash
***** TF-lite matric *****
accuracy = 0.83418359375
model_load_time = 3.2363877296447754
dataset_load_time = 1.5893750190734863
inference_time = 616.6254816055298
inference_time(avg) = 0.581030136834248
IPS = 1.6091366926766768
IPS(inf) = 1.7210811223123745
```

mobilenet v1,v2 추론 결과와 비교하였을 때, 정확도는 조금 높지만 IPS값은 낮아지는 것을 확인 할 수 있었습니다.

**Comment by hyu-leeky** [comment]
오케이. 정애야 잘했다. 그러면 InceptionV3 의 경우 TF2 에서 빌드 된 InceptionV3 모델을 다운 받은 후 이를 tflite 로 변환 후 edge compile 진행. 입력은 uint8 로 변환 후 작업 성공이라고 보면 되는거지? InceptionV3 의 경우 입력은 tfrecord 사용이야? 아니면 이미지를 그대로 사용한거야? 이미지 및 객체인식 쪽 실험은 이제 거의 마무리가 된거지?

**Comment by jungae-park** [comment]
TF2로 작성된 inception v3 모델은 keras에서 API 형태로 제공해주는 모델을 사용하였고, 이를 tflite(uint8)로 변환후 edge compile을 진행하여 모델을 생성하였습니다.
원본 이미지를 사용해서 공홈에서 제공해주는 기본 코드(한 장 추론)에 생성된 모델을 넣어 추론 했을 때 입력 형식 에러 없이 uint8 형태로 잘 추론되어 여러장 추론도 성공하였습니다. 
batch size 1에 대해서는 mobilenet v1, v2, inception v3 모두 진행된 상태이고, batch size를 늘려 추론이 가능한지 확인해봐야합니다.
object detection 경우는 모든 batch size에 따라 실험이 진행된 상태입니다.

**Comment by jungae-park** [comment]
해당 이슈도 close 하겠습니다.
batch size에 따른 이미지 추론에 대한 이슈는  #32 이슈에 기록하겠습니다.
