### ISSUE TITLE
Dockerfile 재구성

### ISSUE THREAD

**Issue by jungae-park** [ddps-lab/edge-inference#40]
tpu 환경에 필요한 라이브러리를 포함하여 재구성 및 docker hub에 이미지 업로드

**Comment by hyu-leeky** [comment]
정애야. 이슈 활용을 조금 더 잘하면 좋을것 같아. 프로젝트 진행하면서 여러 계획을 세우게 되고 진행할 작업을 만들게 될텐데 그런걸 미리 이슈에 만들어두고 하나씩 진행하고 그 중에 일어나는 일을 기록하면 좋을것 같아. 이건을 봐도 이슈를 만들고 바로 PR 을 연계했는데 이상적이라면 이슈를 통해서 여러 이야기를 진행하고 해당 이슈를 resolve 하는 PR 이 생기는게 맞을거야. 지금의 이슈는 단순히 PR 을 만들기 위한 이슈로 보여. 이렇게 하면서 시도를 하는건 좋아. 이제 가능하면 구현이나 연구 관련해서 진행해야 할 작업이나 계획을 작은 단위로 이슈로 생성해두고 거기서 여러 진행상황을 업데이트하고나서 PR 과 연계를 시키도록 하자.
