### ISSUE TITLE
NLP 모델 TFLite 양자화 코드 작성 및 실험

### ISSUE THREAD

**Issue by unhochoi** [ddps-lab/edge-inference#43]

**Comment by unhochoi** [comment]
- 이전 진행 사항
    - RNN, LSTM 모델에 대한 FP16 양자화 완료
        - 배치 단위별 모델을 개별 생성하는 방향으로 진행
        - 해당 모델을 사용한 추론 성능 측정은 향후 진행할 예정
- 추가 진행 사항
    - DistilBERT 모델에 대한 FP16 양자화 완료
        - 기존의 추론 성능 측정에 사용한 DistilBERT 모델은 Hugging Face가 제공하는 모델이었음
        - 하지만, TFLite를 사용해 FP16으로 양자화하기 위해선 양자화하려는 모델이 Tensorflow 기반 모델이여야함
        - 따라서, 사전 훈련된 Hugging Face의 모델을 로드한 뒤, 추가적인 인사이트를 참고해, Tensorflow 기반으로 재훈련한 뒤, 양자화 완료함
    - BERT 모델에 대한 FP16 양자화 진행 중
        - 이전 실험에서, INT8 양자화 시, 입력 형식으로 인한 에러가 발생했었음
        - FP16 양자화 과정에서도 동일한 에러가 발생했으며, 해결 중에 있음

**Comment by hyu-leeky** [comment]
운호야 잘 진행했다. FP16 양자화 시에 TensorRT 사용한것과 비교도 필요할것 같은데, 그렇게 해볼수 있을까? 이슈를 조금 더 구체화해서 양자화 성능 비교로 해서 TensorRT 와 다른 방식의 양자화를 추적하는걸 기록하면 좋을것 같아.

**Comment by unhochoi** [comment]
넵, 해당 부분에 대해 확인해보겠습니다.

**Comment by hyu-leeky** [comment]
운호야 해당 내용은 새로운 이슈로 만들어서 진행하자.

**Comment by unhochoi** [comment]
![Image](https://user-images.githubusercontent.com/28581429/186563958-0beda6c3-9161-44fe-ba52-b60c4ef96add.png)
- 훈련된 Tensorflow BERT 모델의 구조는 위와 같습니다.
  - 훈련된 Tensorflow BERT 모델을 TFLite로 변환한 뒤, TFLite 모델을 사용한 추론 과정에서 발생하고 있는 입출력 에러가, 
  - 기존 Tensorflow 모델의 결과값의 형식이 (None, 2) 이기 때문에 발생하는 에러인지 확인해보기 위해, 
  - 기존 Tensorflow 모델의 네트워크 구조를 변경한 뒤, 재훈련하고, 다시 TFLite로 변경해 추론을 진행 해볼 예정입니다.
    - 네트워크 구조 변경으로 인해 정확도는 저하될 수도 있을 것 같습니다.

**Comment by unhochoi** [comment]
- 기존 Tensorflow BERT 모델의 네트워크 구조를 변경한 뒤, 재훈련하고, 다시 TFLite로 변경해 추론을 진행해보았지만, 동일한 문제로 인해 해결되지 않은 상태입니다.
- 따라서, 우선 BERT 모델을 제외한 RNN, LSTM, DistilBERT 모델에 대해 TensorRT 간 비교를 진행해볼 예정입니다.
