### ISSUE TITLE
Coral TPU 의 성능이 일관적이지 않은 이유에 대한 분석 필요

### ISSUE THREAD

**Issue by hyu-leeky** [ddps-lab/edge-inference#48]
이전 실험 결과 분석에 의하면
Coral TPU 가 Mobilnet V1, MobileNet V2 의 경우 Xavier 보다 높은 처리 성능을 보였지만, InceptionV3 에서의 성능은 좋지않음.
당시에 분석했던 이유중 하나가 InceptionV3 의 경우 Coral 공식 홈페이지에서 모델을 제공해주지 않았다고 했는데, 지금 확인해보면 제공을 해주고 있음.
당시에 해당 내용에 대한 분석이 부족한것 같아서 시간을 내서 조금 더 분석을 해봤으면 함.

**Comment by hyu-leeky** [comment]
첫번째로 코랄 홈페이지에서 제공되는 InceptionV3 의 모델의 추론 성능을 확인해봤으면 함. 이전에 보고했던 결과가 어떻게 차이가 나는지 볼 필요가 있을듯.

**Comment by hyu-leeky** [comment]
다음으로 MobileNetV1, V2 의 경우 원본 모델을 coral 에서 동작하는 모델로 변환해서 추론 시에 성능을 측정해볼 필요가 있을듯 함.

**Comment by jungae-park** [comment]
네 교수님 아래와 같은 순서로 분석해보겠습니다.

1. coral에서 제공해주는 inception v3 모델 추론시 성능 측정 및 기존 측정 값과 비교
2. mobilenet v1, v2 원본 모델을 커스텀 변환 후 추론시 성능 측정 및 기존 측정 값과 비교

**Comment by jungae-park** [comment]
[https://coral.ai/models/all/](https://coral.ai/models/all/)

- coral 공홈에서 분명 모델명이 inception v3라고 나왔지만, 다운로드 받아봤을때 모델명이  inception v2로 다운로드 받아져서 inception v3이 맞는지 조금 의심이 됩니다.
    
![image](https://user-images.githubusercontent.com/46885199/191049347-4a9c05b1-0018-4d4f-8a27-375e1211437d.png)

![image](https://user-images.githubusercontent.com/46885199/191049388-14c98c53-18d2-45b9-870b-cf552f6032c1.png)

- coral 공홈에서 제공해주는 inception v3 추론 결과
    
    ```jsx
    ***** TF-lite matric *****
    accuracy = 0.783796875
    model_load_time = 3.1919474601745605
    dataset_load_time = 0.4738194942474365
    inference_time = 190.98250150680542
    inference_time(avg) = 0.1694372175189892
    IPS = 5.137471850663768
    IPS(inf) = 5.901891064092385
    ```
    
- 기존 coral 공홈에서 제공해주는 mobilenet v1, mobilenet v2, custom-inception v3 추론 성능과 비교
    
![image](https://user-images.githubusercontent.com/46885199/191049470-f02445e5-e5df-4d8a-b45d-9f2200a7c206.png)

* mobilenet v1, v2 보다는 성능이 낮지만, custom으로 convert한 inception v3 모델 보다는 성능이 조금 좋아졌습니다.

**Comment by hyu-leeky** [comment]
오케이. 정애야 빠르게 확인해줘서 좋다.

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/17699616/191125941-4d1a20a3-0dee-4ad1-8134-4057f6568f16.png">

MobileNet 과 InceptionV3 모델의 크기 차이가 클테니 처리 속도 차이는 당연할것 같아. 다른 방향으로 비교를 해보면 coral 공홈 모델과 우리가 변환한 모델의 처리 속도 차이는 크네. 그리고 coral 공홈 버전의 모델은 xavier 와 거의 유사한 성능을 보이는듯 하고.

뭔가 변환 과정에서 놓치는게 있을수 있으니 같이 한번 살펴보자.

그리고 정애가 지적한대로 inceptionv2 모델일수 있다면, 모델의 내부 구조까지 뜯어보기에는 일이 너무 클것 같고, 모델 크기 및 로드 타임 위주로 해서라도 우리가 만든 custom-inceptionV3 와도 얼른 비교해보자.

**Comment by hyu-leeky** [comment]
정애야. 그리고 inceptionV3 의 경우 입력 크기에 따른 모델이 다른데 299에는 inception_V3 이다.

https://raw.githubusercontent.com/google-coral/test_data/master/inception_v3_299_quant_edgetpu.tflite

입력 이미지 크기에 따른 서로 다른 모델인듯 한데, 299 픽셀도 실험 가능 함?

**Comment by jungae-park** [comment]
네 교수님 제가 mobilenet v1, v2의 input size가 244 픽셀이여서 헷갈렸던 것 같습니다.
(원래 실험에서 inception v3의 input size는 299 픽셀입니다.)
coral 공홈에서 제공해주는 inception v3 (299필셀)로 다시 결과를 측정해보고,
저희가 변환한 모델의 성능 비교도 계속 진행해보겠습니다.

**Comment by jungae-park** [comment]
coral 공홈에서 제공해주는 inecption v3(299픽셀) 모델의 추론 결과를 다시 확인하였습니다.

* 기존 coral 공홈에서 제공해주는 mobilenet v1, mobilenet v2, custom-inception v3 추론 성능과 비교
![image](https://user-images.githubusercontent.com/46885199/191154974-7488b58a-1ec4-48a9-bc40-3fd841881810.png)
- coral 공홈에서 제공해주는 inception v3 (299 픽셀) 추론 성능이 저희가 변환하여 사용한 inecption v3 모델 성능과 비슷한 것을 발견하였습니다.
- input size가 244픽셀에 비해서도 성능이 떨어졌습니다.

mobilenet v1, v2 모델도 커스텀 변환을 진행해 성능 비교를 해보겠습니다.

**Comment by hyu-leeky** [comment]
ok. nice to confirm. 어쩌면 코랄은 작은 모델에 최적화 되어 있다고도 볼수 있겠다. Mobilenet V1, V2 까지만 따로 변환해서 본다면 조금 더 실험 결과를 확신할수 있겠다.

**Comment by jungae-park** [comment]
mobilenet v1 모델을 tflite 모델로 convert를 진행하고, edgetpu compiler로 변환하는 과정에서 이슈가 생겨 전달드립니다.

기존 inception v3 모델을 tflite 모델로 convert 했던 방식과 동일하게 mobilenet v1, v2로만 변경하고 input size만 변경 후 convert를 진행하였습니다.
https://encouraging-lantern-5d1.notion.site/convert-code-eddd04bef65046ca8afb74ccd623ac94 (코드)

그리고 edgetpu compiler를 진행하였을 때, mobilenet v2 모델만 정상적으로 완료되었고, mobilenet v1 모델은 아래와 같은 메시지로 컴파일이 되지 않았습니다.
```
Edge TPU Compiler version 15.0.340273435
Invalid model: mobilenetv1.tflite
Model not quantized
```
mobilenet v1은 다른 방식으로 tflite로 convert하는 것이 필요해 보여 확인 중에 있습니다.

mobilenet v2는 tflite convert - edgetpu convert 완료되어 추론을 해보았고, 아래 표로 정리해보았습니다.

<img width="764" alt="image" src="https://user-images.githubusercontent.com/46885199/191225225-c1db2b8b-1c1d-49c4-811b-3a02669a7665.png">

mobilenet v2의 경우 coral 공홈에서 제공해주는 모델보다 정확도가 떨어졌으나, 성능은 조금 더 좋아졌습니다.

**Comment by hyu-leeky** [comment]
응 정애야 잘 정리했다. 이번 이슈에서 확인을 해보고 싶었던건 우리가 진행하는 모델 컴파일이 (tpu 를 위한) TPU 공홈에서 제공되는 모델과 어떤 차이가 있지는 않을런지 확인하는 거였으니, MobileNetV2 로만 진행을 해도 괜찮지 않을까 싶어. 이렇게 보면 우리가 따로 컴파일 하는 모델도 충분히 좋은 성능을 보인다 정도는 결론을 내릴 수 있을것 같아. 내 생각엔 굳이 MobileNetV1 이슈를 해결하지 않아도 괜찮지 않을까 싶어. V2 에 대한 평가가 이루어졌으니.

**Comment by jungae-park** [comment]
네 그럼 convert하는 코드와 컴파일 방법만 git repo에 작성해두고, 실험한 결과값을 기존 메트릭 시트에 정리해 두겠습니다.
