### ISSUE TITLE
엣지에서 모델 로드 타임이 다른 기기에 비해서 ~10배 가량 높은 이유를 분석해보기

### ISSUE THREAD

**Issue by hyu-leeky** [ddps-lab/edge-inference#57]
일반 CPU 장비에서 모델 로드시에는 수초가 소요되는 반면 엣지 장비에서는 1분 정도 소요되는 현상이 괜찮은지 확인 필요

**Comment by jungae-park** [comment]
다른 논문에서 tx2 장비 기준 pytorch 모델 로드 시간을 확인해보았을때, 6~9초 가량만 소요되는 것을 확인하여 저희 실험에서는 어디 부분에서 시간이 많이 소요되고 있는지 확인해보겠습니다.

[zhang-HotEdge18-pCAMP.pdf](https://github.com/ddps-lab/edge-inference/files/9782342/zhang-HotEdge18-pCAMP.pdf)
<img width="308" alt="image" src="https://user-images.githubusercontent.com/46885199/195758809-40b07ea4-a994-49b0-ba3e-3d11ad8143c6.png">

**Comment by hyu-leeky** [comment]
오케이. 참조모델 잘 찾았네. 그렇다면 확인을 하고 넘어가기는 해야겠다.

**Comment by jungae-park** [comment]
우선 기존 사용하던 코드에서 keras에서 제공해주는 모델을 저장하고 불러오는 과정에서 저장하는 시간까지 model load time에 포함된 것이 아닌가 하는 생각에 간단히 mobilenet v1 모델을 저장하는 시간을 제외하고 load하는 시간만 측정해보았습니다.

```
import tensorflow as tf
from tensorflow.keras.applications import mobilenet
import time

image_model = tf.keras.applications.MobileNet(weights='imagenet')
image_model.save(r'./mobilenet')

s=time.time()
tf.keras.models.load_model('./mobilenet')
e=time.time()-s
print(e)
```

같은 코드를 TX2, Colab에서 돌렸을때 아래 처럼 시간 차이가 많이 발생하였습니다.

TX2 device : 59.73223876953125
colab : 4.362516403198242

단순히 로드하는 시간만 측정된 것이라서 저장하는 시간이 포함된 것은 아닌 듯하여 다른 문제가 있었는지 다시 살펴보고 있습니다.

**Comment by hyu-leeky** [comment]
같은 코드인데 그정도로 차이가 난다는거지? 디스크 스토리지의 문제인가.. 이해하기 어려운 수치이기는 하네. 모델 로딩 시간은 모델 의 빈번한 스위치시 중요한 메트릭이니 잘 살펴보도록 하자.

**Comment by jungae-park** [comment]
master 장비와 tx2 장비의 container에서 hdparm, dd로 디스크 성능을 확인해보았습니다.

**[master-ubuntu desktop]**
* cpu core 8, memory 6GB, HDD 916GB
* hdparm
```bash
root@73296e8724a1:/# hdparm -Tt /dev/sda1

/dev/sda1:
 Timing cached reads:   6998 MB in  2.00 seconds = 3504.76 MB/sec
 Timing buffered disk reads: 376 MB in  3.00 seconds = 125.24 MB/sec
```
* dd (write/read)

```bash
root@73296e8724a1:/# dd if=/dev/zero bs=1024 count=1 of=/test_file
1+0 records in
1+0 records out
1024 bytes (1.0 kB, 1.0 KiB) copied, 6.4637e-05 s, 15.8 MB/s
```

```bash
root@73296e8724a1:/# dd if=/test_file of=/dev/null bs=1024
1+0 records in
1+0 records out
1024 bytes (1.0 kB, 1.0 KiB) copied, 3.7226e-05 s, 27.5 MB/s
```

**[tx2]**
* cpu core 4, memory 8GB, SSD 32GB
* hdparm
```bash
root@c6f81a2e98d0:/# hdparm -Tt /dev/mmcblk0p1

/dev/mmcblk0p1:
 Timing cached reads:   3890 MB in  2.00 seconds = 1946.57 MB/sec
 Timing buffered disk reads: 712 MB in  3.00 seconds = 236.97 MB/sec
```
* dd (write/read)
```bash
root@c6f81a2e98d0:/# dd if=/dev/zero bs=1024 count=1 of=/test_file 
1+0 records in
1+0 records out
1024 bytes (1.0 kB, 1.0 KiB) copied, 9.5968e-05 s, 10.7 MB/s
```

```bash
root@c6f81a2e98d0:/# dd if=/test_file of=/dev/null bs=1024
1+0 records in
1+0 records out
1024 bytes (1.0 kB, 1.0 KiB) copied, 0.00020963 s, 4.9 MB/s
```

hdd임에도 불구하고 ssd 보다 성능이 더 좋은 듯하여, 
ssd가 포함된 ec2를 생성하여 비교를 진행해도 될까요?

**Comment by hyu-leeky** [comment]
hdd 가 ssd 보다 성능이 낫다고 판단한 근거는 어떤거야?
만약에 1kb read 로 그런 판단을 내렸다면 전체 크기가 너무 작다. 오히려 hdparm 에서 disk reads 는 ssd 가 더 낫고, 100에서 200 MB/S 정도위 대역폭 이라면 일반적인것 같다는 생각이 들어서.

**Comment by jungae-park** [comment]
네 교수님 일반적인 성능이라면 디스크 성능 문제로 인한 시간 차이라고 볼 수는 없을 것 같아,
tx2 장비에서 다시 keras model save, load 시간을 세세하게 확인해보았습니다.

```bash
import tensorflow as tf
from tensorflow.keras.applications import mobilenet
import time

s1=time.time()
image_model = tf.keras.applications.MobileNet(weights='imagenet')
e1=time.time()-s1
print(e1)

s2=time.time()
image_model.save(r'./mobilenet')
e2=time.time()-s2
print(e2)

s3=time.time()
tf.keras.models.load_model('./mobilenet')
e3=time.time()-s3
print(e3)
```

e1 : 57.57159996032715
e2 : 80.7501311302185
e3 : 61.25472855567932

제가 생각하기에 load_model이 저장되어 있는 pb 모델만 로드한다고 생각했는데 
model을 load하는 시간에 pretraining된 모델을 가져오는 시간이 포함되어 보입니다.
그래서 확실히 저장된 pb 모델을 로드만 하는 것인지 확인해보려고 합니다.

**Comment by jungae-park** [comment]
혹시 몰라, mobilenet v1 torch model layer 생성, 저장, 로드 하는 코드를 실행하여 모델 저장 시간과 로드 시간도 함께 살펴보았습니다.

```
import torch.nn as nn
import torch
import time
from torchsummary import summary

class MobileNetV1(nn.Module):
    def __init__(self, ch_in, n_classes):
        super(MobileNetV1, self).__init__()

        def conv_bn(inp, oup, stride):
            return nn.Sequential(
                nn.Conv2d(inp, oup, 3, stride, 1, bias=False),
                nn.BatchNorm2d(oup),
                nn.ReLU(inplace=True)
                )

        def conv_dw(inp, oup, stride):
            return nn.Sequential(
                # dw
                nn.Conv2d(inp, inp, 3, stride, 1, groups=inp, bias=False),
                nn.BatchNorm2d(inp),
                nn.ReLU(inplace=True),

                # pw
                nn.Conv2d(inp, oup, 1, 1, 0, bias=False),
                nn.BatchNorm2d(oup),
                nn.ReLU(inplace=True),
                )

        self.model = nn.Sequential(
            conv_bn(ch_in, 32, 2),
            conv_dw(32, 64, 1),
            conv_dw(64, 128, 2),
            conv_dw(128, 128, 1),
            conv_dw(128, 256, 2),
            conv_dw(256, 256, 1),
            conv_dw(256, 512, 2),
            conv_dw(512, 512, 1),
            conv_dw(512, 512, 1),
            conv_dw(512, 512, 1),
            conv_dw(512, 512, 1),
            conv_dw(512, 512, 1),
            conv_dw(512, 1024, 2),
            conv_dw(1024, 1024, 1),
            nn.AdaptiveAvgPool2d(1)
        )
        self.fc = nn.Linear(1024, n_classes)

    def forward(self, x):
        x = self.model(x)
        x = x.view(-1, 1024)
        x = self.fc(x)
        return x

if __name__=='__main__':
    # model check
    model = MobileNetV1(ch_in=3, n_classes=1000)
    summary(model, input_size=(3, 224, 224), device='cpu')
    s2=time.time()
    torch.save(model, 'model.pt')
    e2=time.time()-s2
    print(e2)
    s3=time.time()
    model = torch.load('model.pt')
    e3=time.time()-s3
    print(e3)
```

save time : 0.09510517120361328
load time : 0.04020261764526367

그랬을때, 정상적으로 보이는 값으로 측정이 되었습니다.

**Comment by jungae-park** [comment]
edgetpu model load time도 다시 확인하였을 때, 3.13670969초가 걸리는 것으로 보아
keras model을 api로 가지고와 로드하는 시간만 오래 걸리는 듯하여 keras 모델 로드 부분을 다시 살펴보겠습니다.

**Comment by jungae-park** [comment]
기존 keras api를 통해 모델을 save 할 때에는 전체 모델을 하나의 디렉터리에 저장하였었는데,
참고한 자료에 따라 network와 weights 부분을 따로 저장하고 모델을 로드하니 시간이 정상적으로 보입니다.
참고 자료 : https://stackoverflow.com/questions/47455397/extremely-slow-model-load-with-keras
이렇게 구성하여 모델을 로드하고 추론에 사용 될 수 있는지 살펴보겠습니다.

```
import tensorflow as tf
from keras.models import model_from_json
from tensorflow.keras.applications import mobilenet
import time

s1=time.time()
model = tf.keras.applications.MobileNet(weights='imagenet')
e1=time.time()-s1
print(e1)

s2=time.time()
model.save_weights('model.h5')
model_json = model.to_json()
with open('model.json', "w") as json_file:
    json_file.write(model_json)
json_file.close()
e2=time.time()-s2
print(e2)

s3=time.time()
json_file = open("model.json", 'r')
loaded_model_json = json_file.read()
json_file.close()
model = model_from_json(loaded_model_json)
model.load_weights("model.h5")
e3=time.time()-s3
print(e3)
```

save time : 0.6234068870544434
load time : 2.7276453971862793

**Comment by hyu-leeky** [comment]
모델 save 라는게 지금 우리 시나리오에서 왜 필요한지 모르겠네. 지금까지 항상 해왔던거야?
keras 에서 제공해주는 모델을 그냥 불러오는것 아닌가? 아니면 그냥 저장된 모델을 불러와서 (load) 추론 하는게 아닌거야?

**Comment by jungae-park** [comment]
기존 시나리오에서 keras에서 제공해주는 모델을 저장하고, 저장된 모델을 불러와 추론하고 있었습니다.

**Comment by jungae-park** [comment]
이전 실험에서는 keras에서 제공해주는 모델 저장, 로드는 pb 파일 (weight, network)를 사용하였었는데,
이것을 weight(.h5), network(json) 파일로 분리하여 저장하고 로드하니 결과 차이가 있었습니다.

<img width="818" alt="image" src="https://user-images.githubusercontent.com/46885199/196104630-b045585a-0f58-4288-95f6-6f22b0bf0a86.png">


**[model save code]**
```


    model = models_detail[model]
    shutil.rmtree(saved_model_dir, ignore_errors=True)
    #model.save(saved_model_dir, include_optimizer=False, save_format='tf')
    model.save_weights('model.h5')
    model_json = model.to_json()
    with open('model.json', "w") as json_file:
        json_file.write(model_json)
    json_file.close()
```

**[model load code]**
```
model_load_time = time.time()
#model = tf.keras.models.load_model(saved_model_dir)
json_file = open("model.json", 'r')
loaded_model_json = json_file.read()
json_file.close()
model = model_from_json(loaded_model_json)
model.load_weights("model.h5")
model_load_time = time.time() - model_load_time
```

**Comment by hyu-leeky** [comment]
각각의 파일 사이즈는 어떻게 되? 기존의 pb 파일 크기와 h5, json 으로 각각 구분한 파일의 크기.

**Comment by jungae-park** [comment]
<img width="895" alt="image" src="https://user-images.githubusercontent.com/46885199/196110795-745d1bc8-fb91-4e7d-b78f-1163cf13db13.png">

* h5 파일이 바이너리 파일이라 pb 보다 큰 것인지 확인이 필요해보입니다.
https://stackoverflow.com/questions/62079274/difference-between-pb-and-h5

**Comment by hyu-leeky** [comment]
파일 크기의 차이도 크구나. 그런데 지금 다른 경우에는 (예: rpi에서 모델 로드 혹은 수빈/재강 실험에서 모델 로드) pb 파일을 로드해도 빠르게 끝나지 않아? 그 부분도 한번 확인을 해줄래? 아니면 그냥 keras 라이브러리에서 따로 save 하지 않고 keras api 로 바로 로드하면 얼마나 걸리는지 확인해볼래?

**Comment by jungae-park** [comment]
- 수빈이네 실험은 keras api로 모델을 가져와 save하고 save된 것을 load하는 것으로 우리 실험과 방식이 동일합니다.
- keras로 가져온 모델을 save 없이 load 하는 것은
    
    ```bash
    image_model = tf.keras.applications.MobileNet(weights='imagenet')
    ```
    
    이 부분이고, 이것이 가져오는 동시에 로드하는 것으로 57.57159996032715 초가 걸렸었습니다.
    
- keras에서 모델을 가져오는 시간이 포함되어 오래 걸리는 것인가 하여
keras에서 모델을 가져오지 않고 mobilenet v1 모델을 layer로 구성하여 pb(2.2MB)로 local에 저장한 후 로드할때의 시간만 확인 했을 때, 69.81289219856262초가 걸립니다.
- keras에서 모델을 가져온 후, pb(1.9M) 파일로 저장한 것을 로드만 할 때 시간 확인할 때에도 63.02538347244263초가 걸립니다.
- 아무리봐도 pb 모델을 로드하는게 이상하게 오래걸립니다.
- 그런데, yolov5 모델은 keras에서 제공해주는 모델이 아니고, 저장된 pb 모델을 로드하는 것인데 tx2 장비 기준으로 7.86405897140502초가 걸립니다...

**Comment by hyu-leeky** [comment]
음.. 이상하네. 수빈이랑 재강이 실험 결과도 같이 확인을 부탁해봐야겠다.

**Comment by jungae-park** [comment]
네 수빈이네의 실험 결과와 비교하여 크로스 체크 하는 것이 좋을 것 같습니다.
그런데 어제 수빈이와 이야기 나누었을 때 모델 로드 방식이 동일하고 환경의 차이만 있어 정확한 비교가 쉽지 않을 것 같다는 생각이 들었습니다. 같은 방식으로 시간을 체크하지만 결과 값이 달랐기 때문입니다.
그래서 pb 모델을 로드했을때와 h5/json 파일을 로드 했을 때의 차이가 무엇인지를 확인해보는 것이 필요해보입니다.
yolo v5 모델은 keras와 다르게 모델을 어떻게 pb로 생성하였기에 시간 차이가 나는지도 같이 확인해보려고합니다.

**Comment by jungae-park** [comment]
[yolo v5 pb model]
[https://github.com/ultralytics/yolov5/blob/acff977af3a6e23e9c25e932208efed73f9b7810/models/tf.py#L503](https://github.com/ultralytics/yolov5/blob/acff977af3a6e23e9c25e932208efed73f9b7810/models/tf.py#L503)

- yolo v5 torch 기본 모델을 바탕으로 tfmodel로 convert를 진행
- 클래스마다 layer 구성을 한 뒤, pb 파일로 생성
- mobilenet v1을 layer 별로 구성한 pb 파일과 생성 방식의 차이가 없어보임

[nvidia jetson]
- protobuf build 
[https://github.com/ardianumam/Tensorflow-TensorRT/issues/2](https://github.com/ardianumam/Tensorflow-TensorRT/issues/2)
[https://forums.developer.nvidia.com/t/slow-model-loading-on-a-jetson-agx-xavier-with-tensorflow-2-5-0/186131/19](https://forums.developer.nvidia.com/t/slow-model-loading-on-a-jetson-agx-xavier-with-tensorflow-2-5-0/186131/19)
[https://forums.developer.nvidia.com/t/tensorflow-model-loading-takes-longer-or-not-able-to-load/75423/5](https://forums.developer.nvidia.com/t/tensorflow-model-loading-takes-longer-or-not-able-to-load/75423/5)
    - protobuf는 구글에서 개발하여 공개한 직렬화 데이터 구조이다.
    - 텐서플로우는 파일 저장 포맷을 프로토콜 버퍼를 사용한다.
    - nvidia jetson 장치에서 tensorflow 모델 로드시 시간이 오래 걸리는 사례가 많이 있었고, 그 중 protobuf를 build하여 문제를 해결했다는 글들이 많아 추가로 살펴보고 있습니다.

**Comment by jungae-park** [comment]
https://forums.developer.nvidia.com/t/slow-model-loading-on-a-jetson-agx-xavier-with-tensorflow-2-5-0/186131/15

위의 글을 확인하였을 때, tensorflow 모델을 xavier 장치에서 로드하는 시간이 오래 걸린다는 내용이 현재 겪고 있는 문제와 유사하여 보니, 해결책으로 protobuf python 패키지를 다시 빌드하여 해결하였다고 하였습니다.

<img width="683" alt="image" src="https://user-images.githubusercontent.com/46885199/196344211-65edd9f5-1660-481f-b80e-8a677bd9f158.png">

그러나, tensorflow ver 1, jetpack 4.2 기반으로 진행한 것이라 저희 환경 (jetpack 4.6, tensorflow ver 2)에 적용하기에는 이미 tensorflow 2.4 버전이후 부터는 protobuf를 통합하여 따로 빌드하지 않아도 되어 보입니다.
최적화 되었다고 생각이 되는데 여전히 모델 로드 시간이 오래 걸려 다른 사례 및 방법도 찾아보고자합니다.

**Comment by hyu-leeky** [comment]
혹시 수빈 재강이 실험 결과와 비교는 해봤어?

**Comment by jungae-park** [comment]
네 교수님 아래와 같이 확인해보았습니다.

[https://docs.google.com/spreadsheets/d/14Rt9s50BiT4Jdmb2ixyfNz99VtsLi6Sbhd9v-23Tod0/edit#gid=0](https://docs.google.com/spreadsheets/d/14Rt9s50BiT4Jdmb2ixyfNz99VtsLi6Sbhd9v-23Tod0/edit#gid=0)

수빈이가 이전에 공유한 시트의 실험 결과를 비교해보았을 때 
aws intel cpu 기반에서 tensorflow-fp32 모델 로드 시간을 3-6초로 측정한 것이고,
제가 실험한 edge 환경은 arm cpu 기반에서 tensorflow-fp32 모델 로드 시간을 57-69초로 측정하였습니다.
두 실험의 다른 점은 cpu가 intel or arm 에 대한 차이가 있습니다.

- aws intel cpu amd : Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz
- edge device cpu : 
Dual-core NVIDIA Denver 2 64-bit CPU and quad-core Arm® Cortex®-A57 MPCore processor complex

같은 arm 기반의 환경에서 torch 모델 로드 시간을 비교해보면, 
aws arm의 경우 0.9098551273345947초가 걸렸고,
edge arm의 경우 0.04020261764526367초가 걸리기도 하였습니다.

그래서 tensorflow keras 모델이 intel에 최적화되어 arm 기반 환경에서는 로드 시간이 오래 걸리는 것이 아닌가 하는 생각이 듭니다.
[https://community.arm.com/support-forums/f/ai-and-ml-forum/13476/save-tensorflow-model-for-armnn](https://community.arm.com/support-forums/f/ai-and-ml-forum/13476/save-tensorflow-model-for-armnn)

ArmNN용 tensorflow 모델을 이러한 형태로 convert를 진행하여 사용이 필요해 보이기도 합니다.
https://stackoverflow.com/questions/59840850/how-to-convert-tensorflow-model-say-pb-format-to-armnn-armnn-format

```bash
ArmnnConverter -f tensorflow-binary -m {pb_filename} -i {input_layers} -o 
{output_layer} -s {input-size} -p {model_name_after_conversion}
```

**Comment by jungae-park** [comment]
네 교수님 아래와 같이 확인해보았습니다.

[https://docs.google.com/spreadsheets/d/14Rt9s50BiT4Jdmb2ixyfNz99VtsLi6Sbhd9v-23Tod0/edit#gid=0](https://docs.google.com/spreadsheets/d/14Rt9s50BiT4Jdmb2ixyfNz99VtsLi6Sbhd9v-23Tod0/edit#gid=0)

수빈이가 이전에 공유한 시트의 실험 결과를 비교해보았을 때 
aws intel cpu 기반에서 tensorflow-fp32 모델 로드 시간을 3-6초로 측정한 것이고,
제가 실험한 edge 환경은 arm cpu 기반에서 tensorflow-fp32 모델 로드 시간을 57-69초로 측정하였습니다.
두 실험의 다른 점은 cpu가 intel or arm 에 대한 차이가 있습니다.

- aws intel cpu amd : Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz
- edge device cpu : 
Dual-core NVIDIA Denver 2 64-bit CPU and quad-core Arm® Cortex®-A57 MPCore processor complex

같은 arm 기반의 환경에서 torch 모델 로드 시간을 비교해보면, 
aws arm의 경우 0.9098551273345947초가 걸렸고,
edge arm의 경우 0.04020261764526367초가 걸리기도 하였습니다.

그래서 tensorflow keras 모델이 intel에 최적화되어 arm 기반 환경에서는 로드 시간이 오래 걸리는 것이 아닌가 하는 생각이 듭니다.
[https://community.arm.com/support-forums/f/ai-and-ml-forum/13476/save-tensorflow-model-for-armnn](https://community.arm.com/support-forums/f/ai-and-ml-forum/13476/save-tensorflow-model-for-armnn)

ArmNN용 tensorflow 모델을 이러한 형태로 convert를 진행하여 사용이 필요해 보이기도 합니다.
https://stackoverflow.com/questions/59840850/how-to-convert-tensorflow-model-say-pb-format-to-armnn-armnn-format

```bash
ArmnnConverter -f tensorflow-binary -m {pb_filename} -i {input_layers} -o 
{output_layer} -s {input-size} -p {model_name_after_conversion}
```

**Comment by hyu-leeky** [comment]
음.. 지금까지 관찰된 내용에 기반하면 ARM+TF 의 성능이 낮으니 최적화 부분을 생각해볼수도 있기는 하겠네.. 많이 시도를 해본것 같아서 추가적인 디버깅이 난애하기도 해보이네. ARM+TF 쪽의 실험 결과를 조금 더 찾아보면서 마무리를 짓던지 해보자.

**Comment by jungae-park** [comment]
- ARM + TF model load time
    - 관련 문서나 실험을 정리해둔 논문을 찾기 어려움 
    (수치가 포함되어 있는)
    - 라즈베리파이도 ARM 기반이고, 
    tflite or edgetpu-tflite 모델 로드 시간을 보면 3초 이내로 로드 하지만
    - tensorflow model (pb) 모델 로드 시간이 100초가 걸리는 것으로 확인
- ARM + TF vs Intel + TF
    - Intel은 CISC(복잡 명령 집합 컴퓨터)를 사용하여 처리하지만 ARM은 RISC(축소 명령 집합 컴퓨터)를 사용
    - ARM 프로세서는 단일 사이클에서 명령을 실행하기 때문에 기능이 축소되어 있음
    - Intel이 tensorflow 사용에 최적화 되어있는지에 대한 관련 문서도 많이 없음
    https://www.intel.com/content/www/us/en/developer/articles/guide/optimization-for-tensorflow-installation-guide.html
    - ARM은 tensorflow에 많이 최적화되어 있지 않아서 최적화 하는 방법도 따로 있는 듯하고, tensorflow 모델보다는 tflite, edgetpu-tflite와 같이 경량화하여 구조가 간단한 모델을 로드하는 시간이 적게 걸리는 것 같아 보임

그렇다면, pb 모델 로드 시간은 오래 걸리지만 위에서 디버깅하면서 확인하였듯이 h5,network jeson 모델 로드 시간은 적게 걸리니 tensorflow 모델 로드하는 방법을 pb를 사용하지 않고 h5를 사용하여 로드하고 시간을 측정하는 것으로 해야하는지 궁금합니다.

**Comment by hyu-leeky** [comment]
아니면 아예 모델 로딩 시간은 우리 구성 요소에서 제외시키는 방법도 있기는 해.

**Comment by hyu-leeky** [comment]
정애야 혹시 xavier 나 나노에서 TF 에서 모델을 로딩할때 gpu 로 로딩하는지, cpu 로 로딩하는지를 정하는 코드가 있어? 보통 일반적인 컴퓨터 환경에서는 특정 device 를  (cpu 혹은 gpu) 를 지정해서 추론을 진행하던데, 지금 정애가 사용하는 코드에서 모델 로딩 및 추론 시에 특정 디바이스를 지정하는 부분이 있나 싶어서. 만약 있다면 cpu 쪽으로 로딩했을때 시간이 궁금하기도 해.

**Comment by jungae-park** [comment]
1. 기본 tensorflow 모델 로드 코드
```
import tensorflow as tf
import time

s=time.time()
tf.keras.models.load_model('./mobilenet_keras')
e=time.time()-s
print(e)
```
device를 지정하지 않고, 코드를 실행하였을 때 결과는 아래 링크에서 확인해 볼 수 있습니다.
https://encouraging-lantern-5d1.notion.site/tensorflow-133165f7c1cb43a6af1b9a2fb14a0834
링크에서 확인해보면 특정 device를 지정하지 않아도 cuda를 사용하기 때문에 gpu 장치에 접근하는 형태는 확인 됩니다만, 모델 로드시 gpu를 사용하지 않고 htop으로 보았을 때 cpu 사용률이 높아져서 cpu로 모델을 로드한 것으로 확인됩니다. 


2. 실험에서 사용한 추론 코드 (모델 로드 포함)
https://github.com/ddps-lab/edge-inference/blob/main/CNN/image_classification_inference.py#:~:text=gpus%20%3D%20tf.config.experimental.list_physical_devices(%27GPU%27) (14-17 라인)
실험에서 사용한 추론 코드에는 gpu 장치를 지정하는 코드가 포함되어 있지만 이것도 모델 로드시 gpu를 사용하는 것이 아니라 cpu를 사용하고 있었습니다.
추론을 할때에만 gpu를 사용하고 있었습니다.

**Comment by hyu-leeky** [comment]
추론시에 cpu 가 사용된다고 해서 cpu 로 모델이 로드 된다고 보기에 어려운게. 모델은 결국 디스크에 저장되어 있고, 디스크 -> 메모리 -> 캐쉬 -> cpu -> gpu 로 갈수도 있기에 cpu 활용율이 높다고 나올수 있을것 같아.

**Comment by jungae-park** [comment]
1. gpu device 지정 코드 포함하여 첫번째 추론 시간과 두번째 추론 시간 비교
    1. 첫 번째
        
        ```bash
        ***** TF-FP32 matric *****
        user_batch_size = 1
        accuracy = 0.93
        model_load_time = 59.66479182243347
        dataset_load_time = 1.801379919052124
        inference_time = 108.06832766532898
        inference_time(avg) = 0.10634454584121704
        IPS = 5.898499286968969
        IPS(inf) = 9.403397156757801
        ```
        
    2. 두 번째
        
        ```bash
        ***** TF-FP32 matric *****
        user_batch_size = 1
        accuracy = 0.93
        model_load_time = 58.71611189842224
        dataset_load_time = 1.603600263595581
        inference_time = 107.64379477500916
        inference_time(avg) = 0.10598159289360046
        IPS = 5.953668762226049
        IPS(inf) = 9.435600774598129
        ```
        
    3. 세 번째
        
        ```bash
        ***** TF-FP32 matric *****
        user_batch_size = 1
        accuracy = 0.93
        model_load_time = 64.79461479187012
        dataset_load_time = 1.8654108047485352
        inference_time = 111.15161323547363
        inference_time(avg) = 0.10935884857177734
        IPS = 5.623923827072828
        IPS(inf) = 9.144207469811215
        ```

2. cpu device로만 추론이 가능한지 확인
    1. cpu로 모델 로드 시간 확인
        - 현재 붙어있는 device list check
        https://www.gcptutorials.com/article/how-to-list-physical-devices-in-tensorflow
            
            ```bash
            import tensorflow as tf
            physical_devices = tf.config.list_physical_devices()
            for dev in physical_devices:
              print(dev)
            
            ======================output============================
            PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')
            PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')
            ```
            
        - CPU를 강제 사용하고, GPU를 사용하지 않음
            
            ```bash
            import tensorflow as tf
            import time
            import os
            
            os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
            
            s=time.time()
            tf.keras.models.load_model('./mobilenet_keras')
            e=time.time()-s
            print(e)
            root@0603
            ```
            
            [결과 메시지 (cpu)](https://www.notion.so/cpu-c6151d066c0d40e78659a007dd18a320)
            
            ```bash
            59.92244839668274
            ```
            
    2. cpu로 전체 추론 후 확인
        
        [cpu inference code](https://www.notion.so/cpu-inference-code-1f8b2ecd33ab4c85ae5e8158c6913538)
        
        [cpu inference result message](https://www.notion.so/cpu-inference-result-message-405697a130f5480f81bee709c9b26ba6)
        
        ```bash
        ***** TF-FP32 matric *****
        user_batch_size = 1
        accuracy = 0.93
        model_load_time = 57.07873177528381
        dataset_load_time = 1.5995378494262695
        inference_time = 218.79549765586853
        inference_time(avg) = 0.21745626759529113
        IPS = 3.6039421530226847
        IPS(inf) = 4.598625788340599
        ```

결론1. 
cpu로 추론하면 성능도 낮아지고, 추론 시간도 더 오래 걸리는 것으로 보아 gpu를 사용하지 않고 cpu를 잘 사용하고 있는 것 같은데 모델 로드 시간은 줄어들지 않아 모델 로드는 cpu로 계속 로드해왔던 것으로 추정됩니다.

결론2. 
현재 tensorflow 만 설치가 되어 있고, tensorflow-gpu는 설치되어 있지 않지만 gpu 접근 및 사용이 가능한 상태입니다.
그런데, tensorflow-gpu와 tensorflow-cpu가 따로 있는 것으로 보아 각각 gpu, cpu에 최적화 되어 있는 라이브러리로 생각되는데 두 라이브러리를 설치하여 사용되도록 해야 정확하게 gpu 추론/cpu 추론 인 것을 확인을 하는게 좋을지 궁금합니다.

결론3. 
아니면, nvidia jetson 장비가 cpu와 gpu 간의 공유가 가능한지 구조를 확인하는게 더 나을지 궁금합니다.

**Comment by hyu-leeky** [comment]
오케이. 빠른 실험 땡큐. 차례대로 처음에 이야기한 첫번째와 다음의 추론 시간은 지금 보니 전체 이미지 셋에 대한 전체 실험 1, 전체 실험 2를 측정 후 이야기하는듯 한데, 처음에 의미했던건 배치 1로 추론 할때 첫번째 이미지 처리 시간, 두번째 이미지 처리 시간이었어. 아무래도 모델이 로드되어 있지 않다면 첫번째 이미지 추론시 모델 로딩 시간이 길거라고 생각했어.

다음으로 특정코드를 추가하면 추론 시간이 오래 걸리는걸 봐서는 cpu 만 사용하는것 같기는 하네. 이때 gpu 사용율도 확인을 했지? 어쨌든 cpu 만 사용해도 모델로드가 오래 걸리기는 하네. 

그런데 tensorflow-gpu 는 어떤거야? 지금도 gpu 를 사용해서 추론을 하고 있는데, 굳이 어떤 기능을 추가를 하는건지 잘 모르겠네.

결론 3의 경우 cpu, gpu 간의 어떤 공유를 이야기하는지 모르겠네. 기본적으로 RAM 은 서로 공유를 하는걸로 알고 있고.

**Comment by jungae-park** [comment]
네 cpu만 사용하는 추론에서 gpu 사용률이 0%인 것으로 확인했었습니다.

1. 배치 1로 추론 할 때 첫번째 이미지 처리 시간, 두번째 이미지 처리 시간 확인
   
    
    ```bash
    2.9759721755981445 
    0.09648871421813965
    ```
    
    첫번째 이미지 처리 시간과 두번째 이미지 처리시간이 확실히 차이가 있기는 합니다.
    
2. tensorflow-gpu, tensorflow-cpu 
    - tensorflow-gpu, tensorflow-cpu 라이브러리가 따로 존재하고 있어, tensorflow가 gpu와 cpu를 사용하는데 더 최적화된 라이브러리인 줄 알았으나 아닌 것 같습니다.
    - tensorflow 라이브러리만 있어도 gpu 접근 및 사용이 잘 되고 있고, cpu로만으로도 추론이 가능하여 굳이 사용하지 않아도 될 것 같습니다.
3. nvidia jetson 장비가 cpu와 gpu 간의 공유가 가능한지 구조 확인
    1. cpu → gpu로 넘어가기 때문에 시간이 오래 걸리는 것인지 추정
        - 모델을 메모리에 올릴 때 cpu와 gpu가 로드한 모델을 공유하지 못해서 시간이 오래 걸리는 것이 아닌가 하는 생각이 들어 찾아보았습니다.
        [https://forums.developer.nvidia.com/t/the-memory-sharing-between-cpu-and-gpu-in-jetson-tx2/66599](https://forums.developer.nvidia.com/t/the-memory-sharing-between-cpu-and-gpu-in-jetson-tx2/66599)

**Comment by hyu-leeky** [comment]
오케이. 정애야. 클리어. 지난 코멘트에서 궁금한점 해결. 그나저나 딱히 이유에 대한 근거가 나오지는 않네.

**Comment by jungae-park** [comment]
네 교수님 아직 의문이긴 합니다.
조금 더 생각해보겠습니다.

**Comment by jungae-park** [comment]
해당 이슈는 close하고 추후에 필요시 다시 이슈를 생성하겠습니다.
