### ISSUE TITLE
Flask Process 초기화 여부 테스트

### ISSUE THREAD

**Issue by workdd** [ddps-lab/edge-inference#61]
목적 : 요청을 처리할 때 tensorflow load가 발생하지 않도록 구현해야함

Flask에서 요청 route를 받을 때 새로운 process를 사용한다면 load가 될 것이고, 그렇지 않는다면 테스트에 활용가능하여 해당 경우를 테스트 코드 작성하여 확인해볼 예정입니다.

**Comment by workdd** [comment]
동작 테스트 구현

```
from flask import Flask

app = Flask(__name__)

test = 0


@app.route('/')
def request():
    global test
    test += 1
    return str(test) + '\n'


app.run(host="localhost", port=5001)

```

해당 코드로 flask 서버를 띄워 구현했습니다. 혹시 말씀해주신 부분과 같은지 한번 확인 부탁드립니다.

<img width="795" alt="image" src="https://user-images.githubusercontent.com/28581495/218970391-fbce80e9-0a3f-4baf-8248-9cda4805b3b5.png">

테스팅 결과 test = 0 의 초기화가 일어나지 않고 +1 이 된 것을 확인했습니다. Process 초기화가 일어나지 않는 것으로 판단됩니다.

또한 Flask multiprocessing을 검색해보았을 때 의도적으로 multi processing을 사용하는 방법이 있는 것으로 보아 기본적으로 process 초기화가 일어나지 않는 것으로 판단이 됩니다.
https://stackoverflow.com/questions/35616639/python-multiprocessing-in-flask

**Comment by hyu-leeky** [comment]
응 재강아. 지금 결과로는 프로세스 내에서 별도의 쓰레드로 동작을 하는것 같고, TF 라이브러리를 새롭게 로딩하지는 않을것 같은데. 긍정적으로 보인다. 바로 TF 로딩해서  추론을 하게끔 코드를 구성해볼까? 우선 TF 라이브러리 로드 여부를 파악하기 위해서 요청을 받으면 로컬에 저장되어 있는 이미지를 바로 읽어와서 처리를 하게끔 해도 괜찮을것 같아.

**Comment by workdd** [comment]
네 교수님 석현님과 함께 tf가 동작하도록 flask를 구성해보겠습니다 추가적으로 진행시항잇으면 이슈남기겠습니다
