### ISSUE TITLE
edge 장비 백업 및 버전선정 후 재설치

### ISSUE THREAD

**Issue by kh3654po** [ddps-lab/edge-inference#69]
현재 edge 장비들이 ubuntu 18.04를 사용하고 disk의 용량의 대부분을 사용하고 있는데 파악이 안되고 있습니다. 
새롭게 tf serving 이미지를 빌드할겸 실험환경 재구성할겸 ubuntu를 업그레이드하는 등 cuda, tf, python 등의 LTS 최신으로 시스템부터 docker 이미지까지 버전을 통일해서 시스템 구성을 하겠습니다.
백업이 필요할까요?

**Comment by hyu-leeky** [comment]
지금까지 환경 설정에만 너무 많은 시간을 사용해서, 또 다시 환경을 설정하는데 시간을 소요하는게 조금은 꺼려지네. 의미있는 결과물이 나오기도 해야 하고. 지금 상황에서 실험이라도 돌렸으면 하는데 많은 어려움이 있어?

**Comment by kh3654po** [comment]
현재환경에서 실험은 가능한 상태입니다. 환경설정은 나중으로 미뤄도 될것같습니다.

**Comment by hyu-leeky** [comment]
응 그래 석현아. 현재 설정이 최적이 아닐수 있는데, 우선 순위를 조금 조정해서 지금 하는 실험을 마무리지어서 결과물을 만들어 놓고 환경 설정해서 새로운 시도를 해보자.

**Comment by MoohyunSong** [comment]
디스크 용량 관련 Issue로 인해 edge 장비 재설치 작업 진행 중에 있습니다.
현재 Xavier 장비 2개는 NVME SSD를 /에 mount하여 사용하도록 구성 완료했습니다.
tx -> Sata Cable이 아직 배송되지 않아 구성 전입니다.
nano -> Recovery Mode 진입 요구사항이 DC 전원을 요구하여 어댑터 구매 진행중입니다. (현재 카드 사용불가)

현재 구성에 사용된 버전은 Jetpack 4.6.3 입니다.
=> xavier의 경우, JetPack5 도 사용가능하지만, 현 연구실에 있는 tx, nano가 이를 지원하지 않아 (신형 nano는 지원) 동일하게 4.6.3으로 구성중에 있습니다.

edge 장비 구성은 NVIDIA SDK Manager를 통해 Recovery Mode 진입만 하면 클릭 몇번으로 바로 구성가능한 상태입니다.

**Comment by hyu-leeky** [comment]
무현아. 카드는 왜 사용이 불가능한거야? 산단에 전화해서 어떤 이슈인지 물어봤어? 윤서와 이야기해보고 어떤 이슈인지 공유해주면 필요하면 내가 학교에 전화해볼께. 

새롭게 환경 구성하는게 별 이슈없기를 기대해보자 ㅎㅎ

**Comment by MoohyunSong** [comment]
카드의 경우, 결제 내역 처리중 한건이 보류 상태여서 2~3일 지나면 사용이 가능할 예정이라 특별히 해결할 이슈는 아니라고 합니다. 아마 내일 결제가 가능해질 듯 합니다.

**Comment by hyu-leeky** [comment]
무현아. 일단 결제는 가능해. 처리 같은 경우는 다음달 결제일 전에만 처리하면되니, 윤서에게 이야기해서 카드 처리가 거부 되지 않는다면 빨리 사는것도 괜찮을것 같아. 윤서랑 이야기를 나눠보면 좋을것 같아.

**Comment by MoohyunSong** [comment]
한도 초과 메시지가 나와 결제 자체가 안되었던 문제었습니다.
오늘 해당 문제가 해결되어 어댑터 걸제 완료했습니다.

**Comment by MoohyunSong** [comment]
nvidia-tx1, nvidia-tx2 부품 오늘 도착하여 SATA SSD (870 EVO 250GB) 연결 후 세팅 완료했습니다. (JetPack 4.6.3)
Nano DC어댑터는 배송중입니다. (해외배송중이라 이번주 내 도착 예상)

진행상황
- 부품 도착하는 대로 Edge 장비 설정 진행중입니다.
계획
- 논문 발표에 대한 밑그림을 생각해야할 것 같습니다.
- CloudRun 로그 분석 시도해볼 예정입니다. (정확한 추론 시간)
- AWS Summit 참석 예정입니다.
- 웹클라이언트컴퓨팅 프로젝트 빨리 끝내기 위해 노력중입니다.
- Marp theme 관련 회의 진행할 예정입니다. (AWS Summit으로 인해 확실치 않음)

**Comment by hyu-leeky** [comment]
오케이. 무현아. 환경을 새롭게 잡아보고 어떻게 될런지 한번 봐보자.
논문의 경우 결과에 따라서 발표 혹은 포스터가 되기도 해. 리뷰가 오는걸 조금 더 기다려보자.

나머지 부분은 잘 파악하고 진행을 하고 있는듯 하다.

**Comment by MoohyunSong** [comment]
nvidia-nano (1,2) 모두 어댑터 도착하여 recovery mode 진입 성공하였고,

Nvidia SDK 사용하여 nano도 JetPack 4.6.3을 256GB SDCard에 설치 완료했습니다.

이 issue는 close 하겠습니다.

**Comment by hyu-leeky** [comment]
오케이. 다들 수고많았다.
