### ISSUE TITLE
CNN 추론 메모리 부족 에러

### ISSUE THREAD

**Issue by jungae-park** [ddps-lab/edge-inference#7]
**[추가 실험 필요 대상]**
* TX1 장비
1. inception v3 (batch size 64,128)
* Nano 장비
1. mobilenet v1 (batch size 64,128)
2. mobilenet v2 (batch size 32,64,128)
3. inception v3 (모든 batch size)
 
**[기존 실험]**
1. 1000장의 이미지를 batch size 만큼 추론 진행
(batch size가 32일 경우, 각기 다른 32장의 이미지를 약 30번 추론 진행)

**[추가 실험]**
1. 1000장의 이미지 중 batch size 만큼의 같은 이미지 (32장 or 64장)를 batch size 만큼 추론 진행

**Comment by hyu-leeky** [comment]
아 이게 #13  과 같은 내용이었구나. 제목을 보고 다른 내용인줄 알고 새로 만들었네 ㅎㅎ

**Comment by jungae-park** [comment]
넵 교수님이 생성하신 제목과 내용이 더 정확하여 13번 이슈로 정리하겠습니다.
